# fly.toml app configuration file generated for late-lake-6180 on 2023-05-17T14:38:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "late-lake-6180"
primary_region = "yyz"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
